build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: testing # <-- Эта job зависит от job 'testing'. Она выполнится только если 'testing' пройдет успешно.

    permissions:
      contents: read # Разрешение на чтение содержимого репозитория (для checkout)
      packages: write # Разрешение на запись пакетов (для публикации в GHCR)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Добавьте ЭТОТ ШАГ для настройки Buildx ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # <-- Используем action для настройки Buildx

      - name: Login to GitHub Container Registry # Шаг: Вход в GHCR (может быть до или после setup-buildx)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Имя пользователя/организации GitHub
          password: ${{ secrets.GITHUB_TOKEN }} # Встроенный токен GitHub

      - name: Extract metadata (tags, labels) for Docker # Шаг: Генерация тегов и меток
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=
          # Оставьте другие настройки тегов, если они есть

      - name: Build and push Docker image # Шаг: Сборка и публикация образа (теперь Buildx настроен)
        uses: docker/build-push-action@v5
        with:
          context: . # Путь к Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Эти строки кеширования теперь должны работать благодаря setup-buildx-action
          cache-from: type=gha
          cache-to: type=gha,mode=max